version: '2'
volumes:
  db:
  bundle:

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: rails server -b 0.0.0.0
    depends_on:
      - db
    tmpfs:
      - /app/tmp
    environment:
      DATABASE_HOST: db
    working_dir: /app
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    ports:
      - 3000:3000
